### ISSUE TITLE
Nota informativa

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-7#1]
Equipo 7
IBS
[NOTA INFORMATIVA.docx](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-7/files/9897781/NOTA.INFORMATIVA.docx)

**Comment by 11042002** [comment]
Tu calificación es de: 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
